### ISSUE TITLE
Error in .rasterObjectFromFile

### ISSUE THREAD

**Issue by Otoliths** [RS-eco/rasterSp#1]
> library(rasterSp)
> filedir <- "Data/"
> #Calculate amphibian richness
> data(amphibians)
> sr_amphibians <- rasterSR(species_names=amphibians$binomial, path=paste0(filedir, "/SpeciesData/"))
Error in rasterSR(species_names = amphibians$binomial, path = paste0(filedir,  : 
  could not find function "rasterSR"
> sr_amphibians <- calcSR(species_names=amphibians$binomial, path=paste0(filedir, "SpeciesData/"),filename = paste0(filedir, "Species/"))
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)

**Comment by RS-eco** [comment]
I have changed some bits, so it should work now. You need to make sure that you have downloaded the shapefile and created the raster files. The below code should work, but you might have to create the corresponding folders on your computer first:

```
library(rasterSp)
filedir <- "Data/"
if(!dir.exists(paste0(filedir, "/IUCN/AMPHIBIANS"))){
  download.file("http://spatial-data.s3.amazonaws.com/groups/AMPHIBIANS.zip", 
                destfile = paste0(filedir, "/IUCN/AMPHIBIANS.zip")) 
  unzip(paste0(filedir, "/IUCN/AMPHIBIANS.zip"), exdir = paste0(filedir, "/IUCN"))
  unlink(paste0(filedir, "/IUCN/AMPHIBIANS.zip"))
}
r_amphibians <- rasterizeIUCN(dsn=paste0(filedir, "/IUCN/AMPHIBIANS.shp"), resolution=0.5,
                              seasonal=c(1,2), origin=1, presence=c(1,2), 
                              save=TRUE, path=paste0(filedir, "/SpeciesData/"))
data(amphibians)
sr_amphibians <- calcSR(species_names=amphibians$binomial, path=paste0(filedir, "SpeciesData/"))
```
Please let me know, if it works or if you encounter any further problems.

**Comment by Otoliths** [comment]
thank you very much发自我的华为手机-------- 原始邮件 --------发件人： RS-eco <notifications@github.com>日期： 2019年12月18日周三 17:19收件人： RS-eco/rasterSp <rasterSp@noreply.github.com>抄送： Liuyong Ding <ly_ding@126.com>, Author <author@noreply.github.com>主    题： Re: [RS-eco/rasterSp] Error in .rasterObjectFromFile (#1)I have changed some bits, so it should work now. You need to make sure that you have downloaded the shapefile and created the raster files. The below code should work, but you might have to create the corresponding folders on your computer first:
library(rasterSp) filedir <- "Data/" if(!dir.exists(paste0(filedir, "/IUCN/AMPHIBIANS"))){ download.file("http://spatial-data.s3.amazonaws.com/groups/AMPHIBIANS.zip",  destfile = paste0(filedir, "/IUCN/AMPHIBIANS.zip"))  unzip(paste0(filedir, "/IUCN/AMPHIBIANS.zip"), exdir = paste0(filedir, "/IUCN")) unlink(paste0(filedir, "/IUCN/AMPHIBIANS.zip")) } r_amphibians <- rasterizeIUCN(dsn=paste0(filedir, "/IUCN/AMPHIBIANS.shp"), resolution=0.5,  seasonal=c(1,2), origin=1, presence=c(1,2),  save=TRUE, path=paste0(filedir, "/SpeciesData/")) data(amphibians) sr_amphibians <- calcSR(species_names=amphibians$binomial, path=paste0(filedir, "SpeciesData/"))
Please let me know, if it works or if you encounter any further problems.
